package skaro.pokedex.core;

public enum PokedexEnvironment {
	POKEDEX_SHARD_INDEX,
	POKEDEX_SHARD_TOTAL,
	POKEDEX_VERSION,
	POKEDEX_DISCORD_AUTH_TOKEN,
	POKEDEX_PUBLISH_BOTS_DISCORD_AUTH_TOKEN,
	POKEDEX_PUBLISH_CARBONITEX_AUTH_TOKEN,
	POKEDEX_PUBLISH_DISCORD_BOTS_AUTH_TOKEN,
	POKEDEX_DATABASE,
	POKEDEX_DATABASE_USER,
	POKEDEX_DATABASE_PASSWORD,
	POKEDEX_DATABASE_URL,
	POKEDEX_MODEL_PATH,
	POKEDEX_HELP_GIF_PATH,
	POKEDEX_Z_MOVE_PATH,
	POKEDEX_POKEFLEX_BASE_URL,
	POKEDEX_PATREON_AUTH_TOKEN;
}
